#!/bin/bash

xrandr --output DP-0 --rotate right
xrandr --output DP-0 --right-of HDMI-0
xrandr --output DP-2 --rotate inverted
xrandr --output DP-2 --above HDMI-0
xrandr --output DP-4 --left-of HDMI-0

xset s off
xset -dpms
